# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/modification/Arty_Master.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0}]

# IP: bd/system/ip/system_mig_7series_0_0/system_mig_7series_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mig_7series_0_0 || ORIG_REF_NAME==system_mig_7series_0_0}]

# IP: bd/system/ip/system_microblaze_0_0/system_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_0 || ORIG_REF_NAME==system_microblaze_0_0}]

# IP: bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_v10_0 || ORIG_REF_NAME==system_dlmb_v10_0}]

# IP: bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_v10_0 || ORIG_REF_NAME==system_ilmb_v10_0}]

# IP: bd/system/ip/system_dlmb_bram_if_cntlr_0/system_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==system_dlmb_bram_if_cntlr_0}]

# IP: bd/system/ip/system_ilmb_bram_if_cntlr_0/system_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==system_ilmb_bram_if_cntlr_0}]

# IP: bd/system/ip/system_lmb_bram_0/system_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_0 || ORIG_REF_NAME==system_lmb_bram_0}]

# IP: bd/system/ip/system_microblaze_0_axi_periph_0/system_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_periph_0 || ORIG_REF_NAME==system_microblaze_0_axi_periph_0}]

# IP: bd/system/ip/system_microblaze_0_axi_intc_0/system_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_intc_0 || ORIG_REF_NAME==system_microblaze_0_axi_intc_0}]

# IP: bd/system/ip/system_microblaze_0_xlconcat_0/system_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_xlconcat_0 || ORIG_REF_NAME==system_microblaze_0_xlconcat_0}]

# IP: bd/system/ip/system_mdm_1_0/system_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mdm_1_0 || ORIG_REF_NAME==system_mdm_1_0}]

# IP: bd/system/ip/system_rst_mig_7series_0_83M_0/system_rst_mig_7series_0_83M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==system_rst_mig_7series_0_83M_0}]

# IP: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0}]

# IP: bd/system/ip/system_axi_ethernetlite_0_0/system_axi_ethernetlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_ethernetlite_0_0 || ORIG_REF_NAME==system_axi_ethernetlite_0_0}]

# IP: bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_timer_0_0 || ORIG_REF_NAME==system_axi_timer_0_0}]

# IP: bd/system/ip/system_axi_mem_intercon_0/system_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_mem_intercon_0 || ORIG_REF_NAME==system_axi_mem_intercon_0}]

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0}]

# IP: bd/system/ip/system_xbar_1/system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_1 || ORIG_REF_NAME==system_xbar_1}]

# IP: bd/system/ip/system_axi_timer_1_0/system_axi_timer_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_timer_1_0 || ORIG_REF_NAME==system_axi_timer_1_0}]

# IP: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0}]

# IP: bd/system/ip/system_axi_gpio_1_0/system_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_1_0 || ORIG_REF_NAME==system_axi_gpio_1_0}]

# IP: bd/system/ip/system_multiChannelPWM_0_0/system_multiChannelPWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_multiChannelPWM_0_0 || ORIG_REF_NAME==system_multiChannelPWM_0_0}]

# IP: bd/system/ip/system_axi_gpio_2_0_1/system_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_2_0 || ORIG_REF_NAME==system_axi_gpio_2_0}]

# IP: bd/system/ip/system_xadc_wiz_0_0_3/system_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xadc_wiz_0_0 || ORIG_REF_NAME==system_xadc_wiz_0_0}]

# IP: bd/system/ip/system_axi_quad_spi_0_0/system_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_quad_spi_0_0 || ORIG_REF_NAME==system_axi_quad_spi_0_0}]

# IP: bd/system/ip/system_axi_gpio_3_0_1/system_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_3_0 || ORIG_REF_NAME==system_axi_gpio_3_0}]

# IP: bd/system/ip/system_auto_us_0/system_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_0 || ORIG_REF_NAME==system_auto_us_0}]

# IP: bd/system/ip/system_auto_us_1/system_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_us_1 || ORIG_REF_NAME==system_auto_us_1}]

# XDC: bd/system/system_ooc.xdc
