# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/datafiles/emilia/kitchen/modification/rev1/rev1.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0_1/system_axi_gpio_2_0.xci
# IP: The module: 'system_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/datafiles/emilia/kitchen/modification/rev1/rev1.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0_1/system_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/datafiles/emilia/kitchen/modification/rev1/rev1.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0_1/system_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/datafiles/emilia/kitchen/modification/rev1/rev1.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0_1/system_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: e:/datafiles/emilia/kitchen/modification/rev1/rev1.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0_1/system_axi_gpio_2_0.xci
# IP: The module: 'system_axi_gpio_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/datafiles/emilia/kitchen/modification/rev1/rev1.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0_1/system_axi_gpio_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/datafiles/emilia/kitchen/modification/rev1/rev1.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0_1/system_axi_gpio_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: e:/datafiles/emilia/kitchen/modification/rev1/rev1.srcs/sources_1/bd/system/ip/system_axi_gpio_2_0_1/system_axi_gpio_2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
